import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import TanstackProvider from "../provider/TanstackProvider";
import Layout from "../layouts/layout";

import "./globals.css";

export const metadata: Metadata = {
  title: "GroundsApp-App Router",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TanstackProvider>
          <Layout>{children}</Layout>
          <ToastContainer position="top-center" />
        </TanstackProvider>
      </body>
    </html>
  );
}
